"""add default function to uuid columns

Revision ID: 074c49d53fde
Revises: 746fb26bb8ea
Create Date: 2026-05-08 17:17:26.046466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '074c49d53fde'
down_revision: Union[str, Sequence[str], None] = '746fb26bb8ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'frame', ['uuid'])
    op.create_unique_constraint(None, 'refresh_token', ['uuid'])
    op.create_unique_constraint(None, 'user', ['uuid'])
    op.create_unique_constraint(None, 'video', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'refresh_token', type_='unique')
    op.drop_constraint(None, 'frame', type_='unique')
    # ### end Alembic commands ###
