"""add uuid to user, video, frame table

Revision ID: 746fb26bb8ea
Revises: ed9382e208b1
Create Date: 2026-05-08 16:53:35.338569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746fb26bb8ea'
down_revision: Union[str, Sequence[str], None] = 'ed9382e208b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frame', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.add_column('user', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.add_column('video', sa.Column('uuid', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'uuid')
    op.drop_column('user', 'uuid')
    op.drop_column('frame', 'uuid')
    # ### end Alembic commands ###
