"""Add unique constraint to video title per owner

Revision ID: a26eedfa93fc
Revises: 074c49d53fde
Create Date: 2026-05-17 16:08:05.627043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a26eedfa93fc'
down_revision: Union[str, Sequence[str], None] = '074c49d53fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_owner_video_title', 'video', ['owner', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_owner_video_title', 'video', type_='unique')
    # ### end Alembic commands ###
