apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: clip-search
  labels:
    app: qdrant
spec:
  serviceName: qdrant-service
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant
          ports:
            - containerPort: 6333
            - containerPort: 6334
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 1Gi
          volumeMounts:
            - name: volume
              mountPath: /qdrant/storage
      volumes:
        - name: volume
          hostPath:
            path: /home/d568/develop/clip-search/backend/storages/qdrant
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
  namespace: clip-search
  labels:
    app: qdrant
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 6333
      targetPort: 6333
      name: port1
    - port: 6334
      targetPort: 6334
      name: port2
  selector:
    app: qdrant
